version: '3'
services:
  e2e:
    image: cypress
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cypress
    command: npx cypress run
    volumes: 
      - C:/Users/jorge/Desktop/reports/:C:/Users/jorge/Desktop/reports/
      #This is host path local : container path
